name: Build ImmortalWrt for 360P2 (Ubuntu 22.04)

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04  # 使用新环境
    timeout-minutes: 180
    
    env:
      FORCE_UNSAFE_CONFIGURE: 1
      DEBIAN_FRONTEND: noninteractive
      
    steps:
    - name: Checkout ImmortalWrt
      uses: actions/checkout@v4
      with:
        repository: immortalwrt/immortalwrt
        ref: v23.05.3
        submodules: recursive
        fetch-depth: 0

    - name: Install Build Dependencies (Ubuntu 22.04)
      run: |
        sudo apt-get update
        # Ubuntu 22.04 专属依赖
        sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext \
        libssl-dev libxml-parser-perl unzip python3 rsync wget subversion mercurial \
        gperf bison flex texinfo dos2unix libtool-bin u-boot-tools lzma-dev lzma \
        zlib1g-dev libc6-dev-i386 g++-multilib gawk
        
        # 修复 Python 3 兼容性
        sudo ln -sf /usr/bin/python3 /usr/bin/python
        python -m pip install --upgrade pip
        pip install future

    - name: Apply Critical Patches
      run: |
        # procd 修复
        sed -i 's/-Werror //' package/system/procd/Makefile
        
        # hostapd 修复
        echo "CONFIG_WPA_MSG_MIN_PRIORITY=3" >> package/network/services/hostapd/files/hostapd-full.config
        
        # opkg 修复
        sed -i '/PKG_CHECK_MODULES/s/^/#/' package/system/opkg/configure.ac
        
        # Ubuntu 22.04 专属修复
        sed -i 's/ -Wno-format-truncation//' package/libs/libnl-tiny/Makefile
        sed -i 's/ -Wno-format-truncation//' package/network/utils/iwinfo/Makefile

    - name: Configure Target
      run: |
        # 基础配置
        echo "CONFIG_TARGET_ramips=y" > .config
        echo "CONFIG_TARGET_ramips_mt76x8=y" >> .config
        echo "CONFIG_TARGET_ramips_mt76x8_DEVICE_360_360p2=y" >> .config
        echo "CONFIG_TARGET_ROOTFS_SQUASHFS=y" >> .config
        
        # 空间优化
        echo "# CONFIG_IPV6 is not set" >> .config
        echo "# CONFIG_PACKAGE_ppp is not set" >> .config
        echo "# CONFIG_PACKAGE_firewall is not set" >> .config
        
        # 核心功能
        echo "CONFIG_PACKAGE_luci=y" >> .config
        echo "CONFIG_PACKAGE_luci-i18n-base-zh-cn=y" >> .config
        echo "CONFIG_PACKAGE_avahi-daemon=y" >> .config
        echo "CONFIG_PACKAGE_cups=y" >> .config
        echo "CONFIG_PACKAGE_kmod-usb-printer=y" >> .config
        
        # 生成配置
        make defconfig
        make oldconfig

    - name: Compile Firmware (Staged)
      run: |
        # 分阶段编译避免错误
        make tools/compile -j$(nproc) V=sc
        make toolchain/compile -j$(nproc) V=sc
        make target/compile -j$(nproc) V=sc
        make package/compile -j1 V=sc   # 关键步骤单线程
        make package/install -j1 V=sc
        make target/install -j$(nproc) V=s

    - name: Check Firmware
      run: |
        FIRMWARE_PATH="bin/targets/ramips/mt76x8/*squashfs-sysupgrade.bin"
        if [ -f $FIRMWARE_PATH ]; then
          SIZE=$(stat -c%s $FIRMWARE_PATH)
          echo "Firmware size: $SIZE bytes"
        else
          echo "::error::Firmware not generated!"
          find bin/ -type f | xargs ls -lh
          exit 1
        fi

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: immortalwrt-360p2
        path: bin/targets/ramips/mt76x8/*.bin
