name: Build ImmortalWrt for 360P2 (Optimized)

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 90  # 缩短超时时间
    env:
      FORCE_UNSAFE_CONFIGURE: 1
      DEBIAN_FRONTEND: noninteractive
      
    strategy:
      matrix:
        # 并行构建关键组件
        target: [tools, toolchain, packages]
      
    steps:
    - name: Checkout ImmortalWrt
      uses: actions/checkout@v4
      with:
        repository: immortalwrt/immortalwrt
        ref: v23.05.3
        submodules: recursive
        fetch-depth: 1  # 减少克隆深度

    - name: Install Minimal Dependencies
      run: |
        # 仅安装必需依赖
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev \
        zlib1g-dev gawk git gettext libssl-dev unzip python3
        
        # Python 兼容性
        sudo ln -sf /usr/bin/python3 /usr/bin/python

    - name: Apply Critical Patches
      run: |
        # procd 修复
        [ -f "package/system/procd/Makefile" ] && \
          sed -i 's/-Werror=.* //' package/system/procd/Makefile
        
        # 禁用非必要模块
        echo "# CONFIG_PACKAGE_luci-app-firewall is not set" >> .config
        echo "# CONFIG_PACKAGE_iptables is not set" >> .config

    - name: Configure Target
      run: |
        cat << EOF > .config
        CONFIG_TARGET_ramips=y
        CONFIG_TARGET_ramips_mt76x8=y
        CONFIG_TARGET_ramips_mt76x8_DEVICE_360_360p2=y
        CONFIG_TARGET_ROOTFS_SQUASHFS=y
        CONFIG_PACKAGE_luci=y
        CONFIG_PACKAGE_luci-i18n-base-zh-cn=y
        CONFIG_PACKAGE_avahi-daemon=y
        CONFIG_PACKAGE_cups=y
        CONFIG_PACKAGE_kmod-usb-printer=y
        EOF
        
        make defconfig

    - name: Prebuilt Toolchain Setup
      uses: actions/cache@v3
      with:
        path: |
          staging_dir/toolchain-*
          build_dir/toolchain-*
        key: ${{ runner.os }}-toolchain-${{ hashFiles('.config') }}

    - name: Compile Core
      run: |
        # 仅编译必要组件
        make -j$(nproc) V=s \
          package/luci/compile \
          package/avahi/compile \
          package/cups/compile \
          package/kmod-usb-printer/compile \
          2>&1 | tee build.log
        
        # 单独编译问题组件
        make -j1 V=s package/system/procd/compile
        make -j1 V=s package/system/opkg/compile

    - name: Build Minimal Image
      run: |
        # 创建最小化固件
        make -j1 V=s package/install
        make -j1 V=s target/install
        
        # 生成精简固件
        ./scripts/mkits.sh -D ramips/mt76x8 \
          -o bin/targets/ramips/mt76x8/minimal-sysupgrade.bin \
          -k bin/targets/ramips/mt76x8/Image \
          -r bin/targets/ramips/mt76x8/rootfs.squashfs

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: immortalwrt-minimal
        path: bin/targets/ramips/mt76x8/minimal-*.bin
