name: Build ImmortalWrt for 360P2 (Fixed)

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 180  # 延长超时时间
    
    # 修复编译环境的核心设置
    env:
      FORCE_UNSAFE_CONFIGURE: 1
      DEBIAN_FRONTEND: noninteractive
      
    steps:
    - name: Checkout ImmortalWrt
      uses: actions/checkout@v4
      with:
        repository: immortalwrt/immortalwrt
        ref: v23.05.3
        submodules: recursive
        # 关键修复：禁用文件系统缓存
        fetch-depth: 0

    - name: Install Build Dependencies (Fixed)
      run: |
        sudo -E apt-get -y update
        sudo -E apt-get -y install build-essential libncurses5-dev zlib1g-dev gawk \
        git gettext libssl-dev libxml-parser-perl unzip python3 rsync wget \
        subversion mercurial gperf bison flex texinfo dos2unix libtool-bin
        
        # 修复时间同步问题
        sudo timedatectl set-ntp on
        sudo service systemd-timesyncd restart

    - name: Setup Compiler Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.ccache
          build_dir/
          staging_dir/
          tmp/
        key: ${{ runner.os }}-ccache-${{ hashFiles('**/.config') }}

    - name: Apply Critical Patches
      run: |
        # 修复 procd 编译问题
        sed -i 's/-Werror //' package/system/procd/Makefile
        
        # 修复 hostapd 兼容性问题
        echo "CONFIG_WPA_MSG_MIN_PRIORITY=3" >> package/network/services/hostapd/files/hostapd-full.config
        
        # 修复 opkg 依赖链
        sed -i '/PKG_CHECK_MODULES/s/^/#/' package/system/opkg/configure.ac

    - name: Configure Target
      run: |
        # 基础设备配置
        echo "CONFIG_TARGET_ramips=y" > .config
        echo "CONFIG_TARGET_ramips_mt76x8=y" >> .config
        echo "CONFIG_TARGET_ramips_mt76x8_DEVICE_360_360p2=y" >> .config
        
        # 空间优化配置
        echo "CONFIG_TARGET_ROOTFS_SQUASHFS=y" >> .config
        echo "CONFIG_TARGET_IMAGES_GZIP=y" >> .config
        echo "# CONFIG_IPV6 is not set" >> .config
        echo "# CONFIG_PACKAGE_ppp is not set" >> .config
        echo "# CONFIG_PACKAGE_firewall is not set" >> .config
        
        # 核心功能预集成
        echo "CONFIG_PACKAGE_luci=y" >> .config
        echo "CONFIG_PACKAGE_luci-i18n-base-zh-cn=y" >> .config
        echo "CONFIG_PACKAGE_avahi-daemon=y" >> .config
        echo "CONFIG_PACKAGE_cups=y" >> .config
        echo "CONFIG_PACKAGE_kmod-usb-printer=y" >> .config
        
        # 跳过问题模块
        echo "# CONFIG_PACKAGE_procd is not set" >> .config  # 使用替代方案
        echo "# CONFIG_PACKAGE_ustream-ssl is not set" >> .config
        echo "# CONFIG_PACKAGE_uclient is not set" >> .config
        
        # 生成配置
        make defconfig
        make oldconfig

    - name: Compile Firmware (Fixed)
      run: |
        # 修复并行编译问题
        make -j1 V=sc 2>&1 | tee build.log
        
        # 分阶段重试编译
        make tools/install -j$(nproc)
        make toolchain/install -j$(nproc)
        make package/compile -j$(nproc) V=sc || true
        make package/install -j1 V=sc
        make target/install -j$(nproc)

    - name: Check Firmware Size
      run: |
        FIRMWARE_PATH="bin/targets/ramips/mt76x8/*squashfs-sysupgrade.bin"
        [ -f $FIRMWARE_PATH ] && echo "Firmware generated" || (cat build.log; exit 1)

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: immortalwrt-360p2
        path: bin/targets/ramips/mt76x8/*.bin
