name: Build ImmortalWrt for 360P2 (Fixed Prebuilt)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 15  # 更短的超时时间
    
    steps:
    - name: Checkout ImmortalWrt
      uses: actions/checkout@v4
      with:
        repository: immortalwrt/immortalwrt
        ref: v23.05.3
        path: source
        fetch-depth: 1

    - name: Create Directory Structure
      run: |
        # 创建必要的目录结构
        mkdir -p source/staging_dir/toolchain-mipsel_24kc_gcc-12.3.0_musl
        mkdir -p source/build_dir
        mkdir -p source/bin/targets/ramips/mt76x8

    - name: Download Prebuilt Toolchain
      run: |
        cd source/staging_dir/toolchain-mipsel_24kc_gcc-12.3.0_musl
        wget https://downloads.openwrt.org/releases/23.05.3/targets/ramips/mt76x8/openwrt-toolchain-23.05.3-ramips-mt76x8_gcc-12.3.0_musl.Linux-x86_64.tar.xz
        tar -xvf openwrt-toolchain-*.tar.xz --strip-components=1
        rm openwrt-toolchain-*.tar.xz

    - name: Configure Minimal Build
      run: |
        cd source
        
        # 创建最小化配置
        cat << EOF > .config
        CONFIG_TARGET_ramips=y
        CONFIG_TARGET_ramips_mt76x8=y
        CONFIG_TARGET_ramips_mt76x8_DEVICE_360_360p2=y
        CONFIG_TARGET_ROOTFS_SQUASHFS=y
        CONFIG_PACKAGE_luci=y
        CONFIG_PACKAGE_luci-i18n-base-zh-cn=y
        CONFIG_PACKAGE_avahi-daemon=y
        CONFIG_PACKAGE_cups=y
        CONFIG_PACKAGE_kmod-usb-printer=y
        EOF
        
        # 应用配置
        make defconfig

    - name: Build Only Required Packages
      run: |
        cd source
        
        # 设置环境变量
        export STAGING_DIR=$(pwd)/staging_dir
        export PATH=$STAGING_DIR/toolchain-mipsel_24kc_gcc-12.3.0_musl/bin:$PATH
        
        # 仅编译核心包
        make -j$(nproc) package/luci/compile
        make -j$(nproc) package/avahi/compile
        make -j$(nproc) package/cups/compile
        make -j$(nproc) package/kmod-usb-printer/compile
        
        # 获取预编译内核（避免编译内核）
        wget -O bin/targets/ramips/mt76x8/vmlinux https://downloads.openwrt.org/releases/23.05.3/targets/ramips/mt76x8/openwrt-23.05.3-ramips-mt76x8-vmlinux.bin
        
        # 创建根文件系统
        mkdir -p rootfs
        cp -r staging_dir/target-mipsel_24kc_musl/root-ramips/* rootfs/
        
        # 添加编译的包到根文件系统
        for pkg in luci avahi-daemon cups kmod-usb-printer; do
          cp build_dir/target-*/$pkg-*/ipkg/*/*.ipk rootfs/usr/lib/opkg/
        done
        
        # 生成根文件系统镜像
        $STAGING_DIR/host/bin/mksquashfs4 rootfs bin/targets/ramips/mt76x8/root.squashfs -noappend -root-owned -comp xz
        
        # 组合固件
        cat bin/targets/ramips/mt76x8/vmlinux bin/targets/ramips/mt76x8/root.squashfs > bin/targets/ramips/mt76x8/immortalwrt-ramips-mt76x8-360_360p2-squashfs-sysupgrade.bin

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: immortalwrt-360p2
        path: source/bin/targets/ramips/mt76x8/immortalwrt-ramips-mt76x8-360_360p2-squashfs-sysupgrade.bin
