# .github/workflows/build-firmware.yml
name: Build ImmortalWRT for 360P2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ \
        gawk gcc-multilib g++-multilib gettext libncurses5-dev libssl-dev \
        python3-distutils rsync unzip zlib1g-dev subversion git

    - name: Clone ImmortalWRT
      run: |
        git clone https://github.com/immortalwrt/immortalwrt
        cd immortalwrt
        git checkout v24.10.1

    - name: Copy Configuration
      run: |
        cd immortalwrt
        cat <<EOF > .config
        # ImmortalWRT 24.10.1 编译配置（360P2/MT7628AN/16MB）
        # 以下内容为自动生成的完整配置

        kernel:
          version: 5.15
          patches:
            - overlayfs-patch
            - mt7628-usb-fix

        target:
          device: 360P2
          profile: MT7628
          subtarget: mt7628
          features:
            - usb2
            - jffs2
            - squashfs

        packages:
          # 基础系统
          - base-files
          - busybox
          - dnsmasq-full
          - firewall4
          - iptables
          - kmod-fs-ext4
          - kmod-usb-core
          - kmod-usb2
          - kmod-usb-ohci
          - kmod-usb-printer
          - libc
          - libgcc
          - libustream-wolfssl
          - mtd
          - opkg
          - uci
          - uhttpd
          - wpad-basic-wolfssl

          # 打印服务
          - cups
          - cups-bjnp
          - avahi-daemon
          - avahi-dnsconfd
          - p910nd
          - ghostscript
          - foomatic-db
          - foomatic-db-ppds
          - gutenprint

          # 管理界面
          - luci
          - luci-app-cups
          - luci-app-firewall
          - luci-app-opkg

          # 移动端支持
          - avahi-autoipd
          - cups-browsed
          - mdnsresponder

          # 空间优化
          - dropbear
          - nano
          - usbutils

        config:
          # 系统配置
          - CONFIG_TARGET_ROOTFS_PARTSIZE=14
          - CONFIG_TARGET_ROOTFS_JFFS2=y
          - CONFIG_TARGET_JFFS2_ERASEBLOCK=64
          - CONFIG_PACKAGE_kmod-usb-storage=n
          - CONFIG_PACKAGE_kmod-usb-ledtrig-usbport=n
          - CONFIG_PACKAGE_kmod-usb-acm=n
          - CONFIG_PACKAGE_kmod-usb-printer=y
          - CONFIG_PACKAGE_cups-bjnp=y
          - CONFIG_PACKAGE_avahi=y

        custom-feeds:
          - name: cups-drivers
            uri: https://github.com/openwrt/packages.git
            branch: openwrt-24.10
            path: print/cups

          - name: avahi
            uri: https://github.com/lathiat/avahi.git
            branch: v0.8

        image:
          compression: gzip
          compression-level: 9
          partitions:
            - name: firmware
              size: 14M
              type: squashfs

        custom-scripts:
          pre-config: |
            #!/bin/sh
            rm -rf package/feeds/packages/luci-app-*(!cups|!firewall|!opkg)
            rm -rf package/feeds/packages/kmod-*-*(!usb|!fs)
            find package/ -name "usb-storage*" -exec rm -rf {} \;

          post-image: |
            #!/bin/sh
            ./scripts/trimfs.sh
            e2fsck -f ./bin/targets/ramips/mt7628/*.bin

        extra-commands:
          - make -j\$(nproc) package/cups/compile V=s
          - make -j\$(nproc) package/avahi/compile V=s

        dev-mode:
          keep-debug: false
          keep-buildinfo: false
        EOF

    - name: Build Firmware
      run: |
        cd immortalwrt
        make download
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig
        make -j$(nproc) V=s

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: 360P2-Firmware
        path: immortalwrt/bin/targets/ramips/mt7628/*.bin
