name: Build ImmortalWrt for 360P2

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ImmortalWrt
      uses: actions/checkout@v4
      with:
        repository: immortalwrt/immortalwrt
        ref: v24.10.1
        submodules: recursive

    - name: Setup Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext

    - name: Configure Target
      run: |
        echo "CONFIG_TARGET_ramips=y" >> .config
        echo "CONFIG_TARGET_ramips_mt76x8=y" >> .config
        echo "CONFIG_TARGET_ramips_mt76x8_DEVICE_360_360p2=y" >> .config
        echo "CONFIG_PACKAGE_luci=y" >> .config
        echo "CONFIG_PACKAGE_luci-i18n-base-zh-cn=y" >> .config
        echo "CONFIG_PACKAGE_avahi-daemon=y" >> .config
        echo "CONFIG_PACKAGE_cups=y" >> .config
        echo "CONFIG_PACKAGE_kmod-usb-printer=y" >> .config
        make defconfig

    - name: Compile Firmware
      run: make -j$(nproc)

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: immortalwrt-360p2
        path: bin/targets/ramips/mt76x8/*.bin
