name: Build ImmortalWRT for 360P2 with Print Support

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Initialize environment
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ \
        gawk gcc-multilib gettext git libncurses5-dev libssl-dev \
        python3-distutils rsync unzip zlib1g-dev file wget

    - name: Clone ImmortalWRT source
      run: git clone https://github.com/immortalwrt/immortalwrt -b openwrt-24.10

    - name: Configure feeds
      run: |
        cd immortalwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Custom configuration
      run: |
        cd immortalwrt
        cat <<EOF > .config
        #
        # Basic configuration
        #
        CONFIG_TARGET_ramips=y
        CONFIG_TARGET_ramips_mt7628=y
        CONFIG_TARGET_ramips_mt7628_DEVICE_360p2=y

        #
        # Network features
        #
        CONFIG_PACKAGE_dnsmasq=y
        CONFIG_PACKAGE_firewall=y
        CONFIG_PACKAGE_luci=y
        CONFIG_PACKAGE_luci-app-firewall=y
        CONFIG_PACKAGE_luci-i18n-base-zh-cn=y
        CONFIG_PACKAGE_luci-i18n-firewall-zh-cn=y
        CONFIG_PACKAGE_luci-i18n-opkg-zh-cn=y

        #
        # Print services
        #
        CONFIG_PACKAGE_cups=y
        CONFIG_PACKAGE_cups-filters=y
        CONFIG_PACKAGE_cups-bsd=y
        CONFIG_PACKAGE_luci-app-cups=y
        CONFIG_PACKAGE_luci-i18n-cups-zh-cn=y
        CONFIG_PACKAGE_p910nd=y
        CONFIG_PACKAGE_gutenprint=y

        #
        # System optimization
        #
        CONFIG_TARGET_ROOTFS_PARTSIZE=16
        CONFIG_TARGET_ROOTFS_SQUASHFS=y
        CONFIG_TARGET_SQUASHFS_BLOCK_SIZE=131072
        EOF

    - name: Make download
      run: |
        cd immortalwrt
        make download -j8

    - name: Compile firmware
      run: |
        cd immortalwrt
        make -j$(nproc) || make -j1 V=s

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: immortalwrt-360p2-print
        path: immortalwrt/bin/targets/ramips/mt7628/
