name: Build ImmortalWrt for 360P2 (Ultimate)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30  # 超短超时确保快速失败
    
    steps:
    - name: Checkout ImmortalWrt
      uses: actions/checkout@v4
      with:
        repository: immortalwrt/immortalwrt
        ref: v23.05.3
        submodules: false  # 禁用子模块
        path: source
        fetch-depth: 1

    - name: Setup Prebuilt Environment
      run: |
        # 创建预编译环境
        mkdir -p source/staging_dir/{host,target-mipsel_24kc_musl}
        mkdir -p source/build_dir/host
        mkdir -p source/bin
        
        # 下载预编译工具链
        wget https://downloads.openwrt.org/releases/23.05.3/targets/ramips/mt76x8/openwrt-toolchain-23.05.3-ramips-mt76x8_gcc-12.3.0_musl.Linux-x86_64.tar.xz
        tar -xf openwrt-toolchain-*.tar.xz -C source/staging_dir/toolchain-mipsel_24kc_gcc-12.3.0_musl --strip-components=2
        
        # 设置符号链接
        ln -s $(pwd)/source/staging_dir/toolchain-mipsel_24kc_gcc-12.3.0_musl source/staging_dir/toolchain-mipsel_24kc_gcc-12.3.0_musl

    - name: Configure Minimal Build
      run: |
        cd source
        
        # 创建最小化配置
        cat << EOF > .config
        CONFIG_TARGET_ramips=y
        CONFIG_TARGET_ramips_mt76x8=y
        CONFIG_TARGET_ramips_mt76x8_DEVICE_360_360p2=y
        CONFIG_TARGET_ROOTFS_SQUASHFS=y
        CONFIG_PACKAGE_luci=y
        CONFIG_PACKAGE_luci-i18n-base-zh-cn=y
        CONFIG_PACKAGE_avahi-daemon=y
        CONFIG_PACKAGE_cups=y
        CONFIG_PACKAGE_kmod-usb-printer=y
        EOF
        
        make defconfig

    - name: Build Only Required Packages
      run: |
        cd source
        
        # 仅编译核心包
        make -j$(nproc) package/luci/compile
        make -j$(nproc) package/avahi/compile
        make -j$(nproc) package/cups/compile
        make -j$(nproc) package/kmod-usb-printer/compile
        
        # 创建固件结构
        mkdir -p bin/targets/ramips/mt76x8
        cp build_dir/target-*/linux-ramips_mt76x8/vmlinux bin/targets/ramips/mt76x8/
        cp build_dir/target-*/root-ramips/root.squashfs bin/targets/ramips/mt76x8/rootfs.squashfs
        
        # 生成固件
        ./staging_dir/host/bin/padjffs2 bin/targets/ramips/mt76x8/vmlinux
        ./staging_dir/host/bin/mksquashfs4 $(pwd)/build_dir/target-*/root-ramips/ $(pwd)/bin/targets/ramips/mt76x8/root.squashfs -noappend -root-owned -comp xz
        ./staging_dir/host/bin/mkimage -A mips -O linux -T kernel -C none -a 0x80000000 -e 0x80000000 -n "MIPS OpenWrt Linux-5.10" -d bin/targets/ramips/mt76x8/vmlinux bin/targets/ramips/mt76x8/uImage.bin
        ./staging_dir/host/bin/mkimage -A mips -O linux -T filesystem -C none -a 0 -e 0 -n "OpenWrt" -d bin/targets/ramips/mt76x8/root.squashfs bin/targets/ramips/mt76x8/rootfs.bin
        cat bin/targets/ramips/mt76x8/uImage.bin bin/targets/ramips/mt76x8/rootfs.bin > bin/targets/ramips/mt76x8/immortalwrt-ramips-mt76x8-360_360p2-squashfs-sysupgrade.bin

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: immortalwrt-360p2
        path: source/bin/targets/ramips/mt76x8/*.bin
